### ISSUE TITLE
tls 1.2 issue when connecting using ECDHE-ECDSA Cipher

### ISSUE THREAD

**Issue by ayushbindlish** [tempesta-tech/tls-perf#10] opened 2021-04-15 06:27 UTC
```
 ./tls-perf -n 10 --tls 1.2 -c ECDHE-ECDSA-AES256-GCM-SHA384 127.0.0.1 4433
Running TLS benchmark with following settings:
Host:        127.0.0.1 : 4433
TLS version: 1.2
Cipher:      ECDHE-ECDSA-AES256-GCM-SHA384
TLS tickets: off
Duration:    0

( All peers are active, start to gather statistics )
ERROR: cannot establish even one TLS connection: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

```
 openssl s_server -accept :4433 -cert cert_ecdsa_secp384r1_sha384.pem  -key key_ecdsa_secp384r1_sha384.pem  -debug -msg
```

**s_server Error Log:**

```
>>> TLS 1.2, Alert [length 0002], fatal handshake_failure
    02 28
ERROR
140072354628736:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:2284:
shutting down SSL
CONNECTION CLOSED
```

**Comment by krizhanovsky** [comment] 2021-04-15 17:39
The problem has basically the same nature as #9 - the tool was development primarily to test Tempesta TLS.

https://github.com/tempesta-tech/tls-perf/commit/47734ae1eda1f643724a2109e62140f9e25cf628 should fix the problem.

**Comment by ayushbindlish** [comment] 2021-04-16 10:13
Still issues connecting with the said cipher

```
./tls-perf -n 10 --tls 1.2 -c ECDHE-ECDSA-AES256-GCM-SHA384 127.0.0.1 55000
Running TLS benchmark with following settings:
Host:        127.0.0.1 : 55000
TLS version: 1.2
Cipher:      ECDHE-ECDSA-AES256-GCM-SHA384
TLS tickets: off
Duration:    0

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
```

**Comment by krizhanovsky** [comment] 2021-04-16 19:25
Sorry, I made a typo and used wrong exception handling in the previous commit, fixed in https://github.com/tempesta-tech/tls-perf/commit/fe3928bde4b39b77d4edbed53e7598afc04a1769 . I checked the commit with the following and now it work fine. Please confirm that the problem is gone for you.

```
$ openssl req -new -days 365 -nodes -x509 -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -keyout key_ec.pem -out cert_ec.pem
```
```
$ openssl s_server -accept :4433 -cert cert_ec.pem -key key_ec.pem -debug -msg
```
```
$ ./tls-perf -n 10 --tls 1.2 -c ECDHE-ECDSA-AES256-GCM-SHA384 127.0.0.1 4433
Running TLS benchmark with following settings:
Host:        127.0.0.1 : 4433
TLS version: 1.2
Cipher:      ECDHE-ECDSA-AES256-GCM-SHA384
TLS tickets: off
Duration:    0

( All peers are active, start to gather statistics )
TLS hs in progress 0 [10 h/s], TCP open conns 0 [1 hs in progress], Errors 0
========================================
 TOTAL:           SECONDS 1; HANDSHAKES 10
 HANDSHAKES/sec:  MAX 10; AVG 10; 95P 10; MIN 10
 LATENCY (ms):    MIN 7; AVG 7; 95P 9; MAX 9
```

**Comment by krizhanovsky** [comment] 2021-04-21 11:37
Please feel free to reopen the issue if the problem still exists.

**Closed by krizhanovsky** 2021-04-21 11:37 UTC
Labels: bug

**Comment by ayushbindlish** [comment] 2021-05-17 17:43
I just got around checking the latest version. The problem is fixed now and the tool is working as expected.
